# Generated by Django 3.2.8 on 2024-07-26 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('genero', models.CharField(max_length=100, verbose_name='Género')),
                ('autor', models.CharField(max_length=255, verbose_name='Autor')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('direccion_envio', models.TextField(verbose_name='Dirección de envío')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='CarritoLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.carrito')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.libro')),
            ],
            options={
                'verbose_name': 'CarritoLibro',
                'verbose_name_plural': 'CarritosLibros',
            },
        ),
        migrations.AddField(
            model_name='carrito',
            name='libros',
            field=models.ManyToManyField(through='mi_app.CarritoLibro', to='mi_app.Libro'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='mi_app.usuario'),
        ),
    ]
